from __future__ import annotations

"""
File: app/services/order_service.py
Path: app/services/order_service.py
Project: KLResolute WhatsApp SaaS MVP

Purpose:
Persist confirmed single-item orders (Phase 1).

Design rules (LOCKED):
- Write-only service
- No WhatsApp logic
- No menu logic
- No validation beyond basic guards
- Caller must provide final calculated values
- DB is source of truth for timestamps (SA time)
"""

import logging
from dataclasses import dataclass
from typing import Literal

from sqlalchemy.orm import Session
from sqlalchemy import text

logger = logging.getLogger("services.order_service")


DrinkAddon = Literal["NONE", "300ML", "1_5L"]
Flavour = Literal["L", "M", "H"]


@dataclass(frozen=True)
class OrderCreate:
    client_id: str
    customer_msisdn: str

    item_sku: str
    item_name: str
    flavour: Flavour

    base_price: int
    drink_addon: DrinkAddon
    addon_price: int

    total_amount: int
    # confirmed_at deliberately NOT accepted anymore


def create_order(db: Session, order: OrderCreate) -> None:
    """
    Insert a confirmed order into the database.

    Rules:
    - confirmed_at is generated by DB in SA time
    - status is always CONFIRMED
    """

    # -----------------------------
    # Guards
    # -----------------------------
    if not db:
        logger.error("ORDER_CREATE_ABORTED | reason=db_missing")
        return

    if not order:
        logger.error("ORDER_CREATE_ABORTED | reason=order_missing")
        return

    logger.info(
        "ORDER_CREATE_ENTER | client_id=%s | customer=%s | item=%s | total=%s",
        order.client_id,
        order.customer_msisdn,
        order.item_name,
        order.total_amount,
    )

    sql = text(
        """
        INSERT INTO orders (
            client_id,
            customer_msisdn,
            item_sku,
            item_name,
            flavour,
            base_price,
            drink_addon,
            addon_price,
            total_amount,
            confirmed_at,
            status
        )
        VALUES (
            :client_id,
            :customer_msisdn,
            :item_sku,
            :item_name,
            :flavour,
            :base_price,
            :drink_addon,
            :addon_price,
            :total_amount,
            now() AT TIME ZONE 'Africa/Johannesburg',
            'CONFIRMED'
        )
        """
    )

    try:
        db.execute(
            sql,
            {
                "client_id": order.client_id,
                "customer_msisdn": order.customer_msisdn,
                "item_sku": order.item_sku,
                "item_name": order.item_name,
                "flavour": order.flavour,
                "base_price": order.base_price,
                "drink_addon": order.drink_addon,
                "addon_price": order.addon_price,
                "total_amount": order.total_amount,
            },
        )
        db.commit()

        logger.info(
            "ORDER_CREATE_SUCCESS | client_id=%s | customer=%s | item=%s",
            order.client_id,
            order.customer_msisdn,
            order.item_name,
        )

    except Exception as exc:
        try:
            db.rollback()
        except Exception:
            pass

        logger.exception(
            "ORDER_CREATE_FAILED | client_id=%s | customer=%s | err=%s",
            order.client_id,
            order.customer_msisdn,
            exc,
        )
